{% set name = "grunt" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/grunt/-/grunt-{{ version }}.tgz
  sha256: a65971e59524569f8b984f0822706ce00cee340cc78eea34067611316a53c706

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs
  
test:
  commands:
    - grunt --help

about:
  home: https://github.com/gruntjs/grunt
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: 'Grunt: The JavaScript Task Runner '
  description: |
    The JavaScript Task Runner 
  doc_url: http://gruntjs.com/
  dev_url: https://github.com/gruntjs/grunt

extra:
  recipe-maintainers:
    - danielnachun
    - cshaley
    - sannykr
