{% set name = "grunt" %}
{% set version = "1.0.4" %}
{% set sha256 = "da6b181efc81ef19d6d04a5e83a090eeb7b6b58464d6ad1b1ef47a86a7730141" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gruntjs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g grunt
  requires:
    - nodejs
   

about:
  home: https://github.com/gruntjs/grunt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Grunt: The JavaScript Task Runner '
  description: |
    The JavaScript Task Runner 
  doc_url: http://gruntjs.com/
  dev_url: https://github.com/gruntjs/grunt

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
