schema_version: 1

context:
  version: "1.6.2"

package:
  name: grunt
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/grunt/-/grunt-${{ version }}.tgz
  sha256: a782f2aaa2e2e13a432525c35072fbf0c11295079c2722d90ff9a322ec5b5d1a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - grunt --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Grunt: The JavaScript Task Runner "
  description: |
    The JavaScript Task Runner
  homepage: https://github.com/gruntjs/grunt
  repository: https://github.com/gruntjs/grunt
  documentation: http://gruntjs.com/

extra:
  recipe-maintainers:
    - danielnachun
    - cshaley
    - sannykr
