travis:
  secure:
    BINSTAR_TOKEN: lIpd8nD5Cv7Cf4n5zNbLad9/CDAEMY1zm+J8fzgQZxxkTU+N5fq716Gg7G6IubgEKo4FhSpZq2tqqXFCi0VbcQYpM72PqjN/gZPMuHZ6AdYtlcYxpHu3gbgeWaRVZX0oXFdDo3j3BeEORo9JZThTohnHaf5QqyoeZwESF4KVydJyPmoqfMhSqZr2CAyrCMb09BZn7fdIQbyLe7V4VLARaKUx8kZsEDKdawWJ126QrukJiD0u6xG9Uy5VacDr10t8mRN+WeZ2HhRM4vf8GphRBFkbYShlnB3YkcHm1BM44dCMVKUDooyBuFwbrCVoDzEoKGTGollLnXIs95Zu/VKVn0KSAs+Ru4d1d6vu2TXBx8majsiW+0jRVttr9nIAbaG3wyYq59PGCmZSS+r/AIqzbeMcyT88VPzVKHfiZ2IeSivSFLSGQjt+6L+ukGH0fSUo74NU6JldtpO78BagrgMYQjLRjYOEH8UT+DH/ANaFPXG+ExR/RInCMbf/8QKWzC0mjV57gNBBzsgWWqjWeD/ZRYXIhlyif1voJM7lSq29BP9ezsiwo+RE06Zc6QMdqU7S0XpEXTbrigUyzmg1U28Dl2Yp2oyfRHeoyqQDDFaab8PXsQ2zWix6frtRleCk0t4ZR+O35K2IbI0xZ7E4M9nBxrQGJmBLo6ftb7q5MXrNYB0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
