travis:
  secure:
    BINSTAR_TOKEN: k/9OaTWTkC7Lzo7/IHqH9gtN1ndM02URb38Xh/fqzqAFGN1HizJUanvXbm6GJlwpkj1WbgYzgdb/h9ZKethQ9zgVirKwINWMbVhtY+Ez7vEQZH58I9Pp+jOgbIALSsKjBRZQnJ2NaxSucmClvZokn3tTr8ZeI1TT80G7u74Sr2Bqtfbo+wMepr0HlC85vP6+llHExHfT06K8aoXTUhHb9JGLgRuhVLL0IuLB53eBBRa3JFEvfQzGI7meTJzF7oXqs2IpG2ZVcjPVShIXc6zbtZvI9ZC9s7x+IPU9pT8oIH42Efy0JQkEgd44vE3slWcXMRE3gEFkXptTWIFyFFbDyn1CCpTwmwO3yNrkx5tbTpRIxqqUnlVA2MjpqO5u524uJLhyacBJU+2dxa1EmBOcGt63ZY2QHfOq7/PdSdfZnca9kIXPIY60PfYxSPPn2TVQNlooY5wXQvr3Iom6rbm4AxRNJdctbAd2KWCzUExAxPmPPgOBYpS8QEsufNHtHgOIYSmgQfpNCPl2VUImepTTI151FC7Yxx+42lsuqwBeRW52sa+6cjzP0PNlfXMtJ9soJEbgxwoDTDOdPhvj5ViNK+cxxSbmHn+CTwJq8/LHWCR8jje6BrHHE+UQ8HbEYWUigmC/F0mJ6elRQtTFTLgdNeovcZxGQzCpsIZ28uyNyyI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
