travis:
  secure:
    BINSTAR_TOKEN: 0zZOjSDu5Q0qepzfk3e+e04zLWpAVEZPGbQSjrpDnXMUPgO5wkVENd1s/5H00AJAsI3OIboCWX01oYJ0DvhjIKBYINtygIzUNer8wksgSTitEE6y6cv15c4GKMy/fiwAJ74w1/Ks6BgYM8VqPptBkZizeUivM3dNVrudbmN4WGQqEm99hYYmVxU8JOwR4q/6KwCyc0PONncB+PtFxkbaeohmRzfVB6P/fqLNkfNMpHiPvaUcKDL1U3wzZZGmESy4wFUK10qAg9a2UXfNzsRaaaY8iwYzwM/Rxn0Uu2bHC+7Rknv8WrGRExPYdbrtlKdvI6Zd/n6txB/Jj0Ml8l7v642Yl+PdCZQKO1KfpRWrXsN2hmcS0mlmznMnRpWbSPrzs8gKMt3N1+IEMN7NZEPJ1lKflQ2W4MMQFYMVrjInXX5zompFGBQC7Fb1zlizP1nfhpN45Le0HKzhHuH+OJz3HAwFZAHl9zYcA9ygJfcbcsnChL/prSxqO7UvqpmpRAVVq/9NdJNr+EFUDs/NKklhZEi7ZADmQhfAMqfQHvPRzcqpDbKDcf/2U4HGHGmfNSpT/42IQNZscxp96s9zxsAWo6UvxVqSRm6Dnl+WNKuVzJKaKZ0f2vC1RRh98wZsvDC+s1cop959/K+azIm1lJQevOuMy7oA8kuMYVa+2ocq75M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
